import { MetadataRoute } from 'next';
import { SITE_URL } from '../seo-config';

/**
 * robots.txt
 * Auto-generated by Next.js at build time → /robots.txt
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/api/', '/_next/'],
      },
      {
        /* Block AI scrapers if desired — remove if you want AI indexing */
        userAgent: 'GPTBot',
        disallow: '/',
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
