import { MetadataRoute } from 'next';
import { SITE_URL } from '../seo-config';
import { servicesDetailsData } from '../services-data';
import { exercisesData } from '../exercises-data';

/**
 * Dynamic sitemap.xml
 * Auto-generated by Next.js at build time → /sitemap.xml
 * Submitted to Google Search Console for faster indexing.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  /** Static pages with priority + change frequency */
  const staticRoutes: MetadataRoute.Sitemap = [
    {
      url: `${SITE_URL}/`,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 1.0,
    },
    {
      url: `${SITE_URL}/about-us`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: `${SITE_URL}/services`,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 0.95,
    },
    {
      url: `${SITE_URL}/home-visits`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/exercises`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/faq`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/contact-us`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.9,
    },
  ];

  /** Service category deep-links */
  const serviceCategories = ['ortho', 'neuro', 'special', 'technique'];
  const categoryRoutes: MetadataRoute.Sitemap = serviceCategories.map((cat) => ({
    url: `${SITE_URL}/services?cat=${cat}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.7,
  }));

  /** Individual service detail pages indexed dynamically */
  const serviceDetailRoutes: MetadataRoute.Sitemap = Object.keys(servicesDetailsData).map((slug) => ({
    url: `${SITE_URL}/services/${slug}`,
    lastModified: now,
    changeFrequency: 'weekly' as const,
    priority: 0.85,
  }));

  /** Individual exercise detail pages indexed dynamically */
  const exerciseDetailRoutes: MetadataRoute.Sitemap = Object.keys(exercisesData).map((slug) => ({
    url: `${SITE_URL}/exercises/${slug}`,
    lastModified: now,
    changeFrequency: 'weekly' as const,
    priority: 0.8,
  }));

  return [
    ...staticRoutes,
    ...categoryRoutes,
    ...serviceDetailRoutes,
    ...exerciseDetailRoutes
  ];
}
