import { MetadataRoute } from 'next';
import { SITE_URL } from '../seo-config';

/**
 * Dynamic sitemap.xml
 * Auto-generated by Next.js at build time → /sitemap.xml
 * Submitted to Google Search Console for faster indexing.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  /** Static pages with priority + change frequency */
  const staticRoutes: MetadataRoute.Sitemap = [
    {
      url: `${SITE_URL}/`,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 1.0,
    },
    {
      url: `${SITE_URL}/about-us`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: `${SITE_URL}/services`,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 0.95,
    },
    {
      url: `${SITE_URL}/home-visits`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/exercises`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/faq`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/contact-us`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.9,
    },
  ];

  /**
   * Service category deep-links — each category URL gets its own sitemap entry
   * so search engines index /services?cat=ortho style pages too.
   * NOTE: If you later add individual service detail pages (/services/back-pain),
   * add them here dynamically from a CMS or data source.
   */
  const serviceCategories = ['ortho', 'neuro', 'special', 'technique'];
  const categoryRoutes: MetadataRoute.Sitemap = serviceCategories.map((cat) => ({
    url: `${SITE_URL}/services?cat=${cat}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.7,
  }));

  return [...staticRoutes, ...categoryRoutes];
}
